- name: NAS Playbook
  hosts: pis
  user: pi
  become: yes
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install packages
      become: yes
      apt:
        pkg:
          - ntfs-3g
    - name: Create Primary Mount Points
      file:
        path: /mnt/primary-exthdd
        state: directory
    - name: Create Secondary Mount Points
      file:
        path: /mnt/backup-exthdd
        state: directory
    - name: Mount Primary
      ansible.posix.mount:
        path: /mnt/primary-exthdd
        src: LABEL={{nas.primary_drive_label}}
        state: mounted
        fstype: ntfs
    - name: Mount secondary
      ansible.posix.mount:
        path: /mnt/backup-exthdd
        src: LABEL={{nas.backup_drive_label}}
        state: mounted
        fstype: ntfs
    - name: Copy nas-rsync file
      copy:
        src: ./files/nas-rsync.sh
        dest: /usr/local/bin/nas-rsync.sh
        mode: '544'
    - name: Setup cron job to sync HDDs everyday 1 AM local time
      ansible.builtin.cron:
        name: rsync-job
        minute: "0"
        hour: "1"
        job: "/usr/local/bin/nas-rsync.sh"
        state: present
- name: Setup emailing rsync report
  import_playbook: nas-email.yml